name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      # Tips on Go binary:
      # https://github.com/actions/setup-go/issues/27#issuecomment-549102955
      - name: Build
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          make install
          make build

      - name: Create a release and upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          tag_name="${GITHUB_REF##*/}"

          gh release create $tag_name --generate-notes
          gh release upload $tag_name $(find build -name "release_*.zip" -type f | tr '\n' ' ')
