name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup runtime
        uses: actions/setup-go@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Build
        run: |
          make install
          make build

      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x

          assets=()

          for a in ./build/*.zip ; do
            assets+=("-a" "$asset")
          done

          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "$tag_name" $"tag_name"
