name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Tips on Go binary:
      # https://github.com/actions/setup-go/issues/27#issuecomment-549102955
      - name: Build
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          make install
          make build
        env:
          QUILL_SIGN_P12:      ${{ secrets.APPLE_P12_BASE64_ENCODED }}
          QUILL_SIGN_PASSWORD: ${{ secrets.APPLE_P12_PASSWORD }}

      - name: Create a release and upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          tag_name="${GITHUB_REF##*/}"

          gh release create $tag_name --generate-notes
          gh release upload $tag_name $(find build -name "release_*.zip" -type f | tr '\n' ' ')
