name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      # Tips on Go binary:
      # https://github.com/actions/setup-go/issues/27#issuecomment-549102955
      - name: Build
        run: |
          go get github.com/mitchellh/gox
          export PATH=${PATH}:`go env GOPATH`/bin
          make build

      - name: Create a release and upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          tag_name="${GITHUB_REF##*/}"

          gh release create $tag_name --generate-notes

          assets=()

          for asset in ./build/*.zip ; do
            assets+=(" " "$asset")
          done

          gh release upload $tag_name "${assets[@]}"
