name: Test on Linux

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup runtime
        uses: actions/setup-go@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Test
        run: make test

      - name: Upload report to Codecov
        run: bash <(curl -s https://codecov.io/bash)
